AppGCT/AppGCT.csproj
AppGCT/Data/AppGCTContext.cs
AppGCT/Migrations/20230410123021_teste2.Designer.cs
AppGCT/Migrations/20230410123021_teste2.cs
AppGCT/Migrations/20230410134408_teste3.Designer.cs
AppGCT/Migrations/20230410134408_teste3.cs
AppGCT/Migrations/20230410140116_remocaoErro.Designer.cs
AppGCT/Migrations/20230410140116_remocaoErro.cs
AppGCT/Migrations/20230410142159_CRUDGinastas.Designer.cs
AppGCT/Migrations/20230410142159_CRUDGinastas.cs
AppGCT/Migrations/20230410145034_CRUDGinastas1.Designer.cs
AppGCT/Migrations/20230410145034_CRUDGinastas1.cs
AppGCT/Migrations/20230410151504_CRUDGinastas2.Designer.cs
AppGCT/Migrations/20230410151504_CRUDGinastas2.cs
AppGCT/Models/Ginasta.cs
AppGCT/Pages/Inscricoes/Create.cshtml
AppGCT/Pages/Inscricoes/Create.cshtml.cs
AppGCT/Pages/Inscricoes/Delete.cshtml
AppGCT/Pages/Inscricoes/Delete.cshtml.cs
AppGCT/Pages/Inscricoes/Details.cshtml
AppGCT/Pages/Inscricoes/Details.cshtml.cs
AppGCT/Pages/Inscricoes/Edit.cshtml
AppGCT/Pages/Inscricoes/Edit.cshtml.cs
AppGCT/Pages/Inscricoes/Index.cshtml
AppGCT/Pages/Inscricoes/Index.cshtml.cs
AppGCT/Pages/Shared/_Layout.cshtml

Criação do CRUD da tabela Ginastas

Criação de CRUD da tabela Ginastas

---

AppGCT/Areas/Identity/Data/Utilizador.cs
AppGCT/Areas/Identity/Pages/Account/Manage/Index.cshtml
AppGCT/Areas/Identity/Pages/Account/Manage/Index.cshtml.cs
AppGCT/Areas/Identity/Pages/Account/Register.cshtml.cs
AppGCT/Data/ModelBuilderExtensions.cs
AppGCT/Migrations/20230410162500_numsocio.Designer.cs
AppGCT/Migrations/20230410162500_numsocio.cs

Inclusão do Nº Sócio no Model Utilizador;
Perfil passa a mostrar o Número de Sócio;

inclusão Número de Sócio

---

AppGCT/Data/AppGCTContext.cs
AppGCT/Migrations/20230514113923_initialCreate.Designer.cs
AppGCT/Migrations/20230514113923_initialCreate.cs
AppGCT/Migrations/20230514141718_initialCreate1.Designer.cs
AppGCT/Migrations/20230514141718_initialCreate1.cs
AppGCT/Models/Epoca.cs
AppGCT/Models/Ginasta.cs
AppGCT/Models/Inscricao.cs
AppGCT/Pages/Inscricoes/Ginastas/Edit.cshtml.cs
AppGCT/Pages/Inscricoes/InscricaoEpoca/Create.cshtml
AppGCT/Pages/Inscricoes/InscricaoEpoca/Create.cshtml.cs
AppGCT/Pages/Inscricoes/InscricaoEpoca/Delete.cshtml
AppGCT/Pages/Inscricoes/InscricaoEpoca/Details.cshtml
AppGCT/Pages/Inscricoes/InscricaoEpoca/Details.cshtml.cs
AppGCT/Pages/Inscricoes/InscricaoEpoca/Edit.cshtml
AppGCT/Pages/Inscricoes/InscricaoEpoca/Edit.cshtml.cs

Inclusão da Epoca como chave forasteira na tabela Inscrição

Adicionar epoca à inscricao

---

AppGCT/Data/AppGCTContext.cs
AppGCT/Migrations/20230521163206_initialCreate.Designer.cs
AppGCT/Migrations/20230521163206_initialCreate.cs
AppGCT/Migrations/AppGCTContextModelSnapshot.cs
AppGCT/Models/Classe.cs
AppGCT/Models/Inscricao.cs
AppGCT/Pages/Inscricoes/InscricaoEpoca/Create.cshtml
AppGCT/Pages/Inscricoes/InscricaoEpoca/Create.cshtml.cs
AppGCT/Pages/Inscricoes/InscricaoEpoca/Delete.cshtml
AppGCT/Pages/Inscricoes/InscricaoEpoca/Delete.cshtml.cs
AppGCT/Pages/Inscricoes/InscricaoEpoca/Details.cshtml
AppGCT/Pages/Inscricoes/InscricaoEpoca/Details.cshtml.cs
AppGCT/Pages/Inscricoes/InscricaoEpoca/Edit.cshtml
AppGCT/Pages/Inscricoes/InscricaoEpoca/Edit.cshtml.cs
AppGCT/Pages/Inscricoes/InscricaoEpoca/Index.cshtml
AppGCT/Pages/Inscricoes/InscricaoEpoca/Index.cshtml.cs

Inclusão FK IdClasse nas Inscrições;
Alteração do CRUD Inscrição para contemplar a FK;

Inclusão FK IdClasse nas Inscrições;

---

AppGCT/Data/AppGCTContext.cs
AppGCT/Migrations/20230524193940_initialCreate.Designer.cs
AppGCT/Migrations/20230524193940_initialCreate.cs
AppGCT/Migrations/AppGCTContextModelSnapshot.cs
AppGCT/Models/Classe.cs
AppGCT/Models/Desconto.cs
AppGCT/Models/Rubrica.cs
AppGCT/Pages/Gestao/Index.cshtml
AppGCT/Pages/Gestao/RubricasPrecario/Create.cshtml
AppGCT/Pages/Gestao/RubricasPrecario/Create.cshtml.cs
AppGCT/Pages/Gestao/RubricasPrecario/Delete.cshtml
AppGCT/Pages/Gestao/RubricasPrecario/Delete.cshtml.cs
AppGCT/Pages/Gestao/RubricasPrecario/Details.cshtml
AppGCT/Pages/Gestao/RubricasPrecario/Details.cshtml.cs
AppGCT/Pages/Gestao/RubricasPrecario/Edit.cshtml
AppGCT/Pages/Gestao/RubricasPrecario/Edit.cshtml.cs
AppGCT/Pages/Gestao/RubricasPrecario/Index.cshtml
AppGCT/Pages/Gestao/RubricasPrecario/Index.cshtml.cs

Atualização dos model's Classe e Desconto;
Criação model Rubrica;
Criação CRUD inicial Rubrica;

Criação Model Rubrica;

---

AppGCT/Data/AppGCTContext.cs
AppGCT/Migrations/20230531191203_initialCreate.Designer.cs
AppGCT/Migrations/20230531191203_initialCreate.cs
AppGCT/Migrations/AppGCTContextModelSnapshot.cs
AppGCT/Models/Classe.cs
AppGCT/Models/Desconto.cs
AppGCT/Models/Rubrica.cs
AppGCT/Pages/Gestao/RubricasPrecario/Create.cshtml
AppGCT/Pages/Gestao/RubricasPrecario/Create.cshtml.cs
AppGCT/Pages/Gestao/RubricasPrecario/Delete.cshtml
AppGCT/Pages/Gestao/RubricasPrecario/Details.cshtml
AppGCT/Pages/Gestao/RubricasPrecario/Edit.cshtml
AppGCT/Pages/Gestao/RubricasPrecario/Edit.cshtml.cs
AppGCT/Pages/Gestao/RubricasPrecario/Index.cshtml
AppGCT/Pages/Gestao/RubricasPrecario/Index.cshtml.cs

Correção relação Rubricas para Descontos

Rubricas upd

---

AppGCT/Migrations/20230601203630_initialCreate.Designer.cs
AppGCT/Migrations/20230601203630_initialCreate.cs
AppGCT/Migrations/AppGCTContextModelSnapshot.cs
AppGCT/Models/Rubrica.cs
AppGCT/Pages/Gestao/RubricasPrecario/Create.cshtml
AppGCT/Pages/Gestao/RubricasPrecario/Create.cshtml.cs
AppGCT/Pages/Gestao/RubricasPrecario/Delete.cshtml
AppGCT/Pages/Gestao/RubricasPrecario/Delete.cshtml.cs
AppGCT/Pages/Gestao/RubricasPrecario/Details.cshtml
AppGCT/Pages/Gestao/RubricasPrecario/Details.cshtml.cs
AppGCT/Pages/Gestao/RubricasPrecario/Edit.cshtml
AppGCT/Pages/Gestao/RubricasPrecario/Edit.cshtml.cs
AppGCT/Pages/Gestao/RubricasPrecario/Index.cshtml
AppGCT/Pages/Gestao/RubricasPrecario/Index.cshtml.cs

Atualização CRUD Rúbricas

---

AppGCT/Pages/Gestao/RubricasPrecario/Create.cshtml
AppGCT/Pages/Gestao/RubricasPrecario/Create.cshtml.cs

Inclusão de validações nas rúbricas

Rubricas validacoes

---

AppGCT/Pages/Gestao/Index.cshtml
AppGCT/Pages/Precario/Index.cshtml
AppGCT/Pages/Precario/Index.cshtml.cs
AppGCT/Pages/Shared/_Layout.cshtml

Inclusão secção Preçário público

Inclusão secção Preçário público

---

AppGCT/Pages/Gestao/RubricasPrecario/Create.cshtml
AppGCT/Pages/Gestao/RubricasPrecario/Create.cshtml.cs
AppGCT/Pages/Gestao/RubricasPrecario/Edit.cshtml
AppGCT/Pages/Gestao/RubricasPrecario/Edit.cshtml.cs
AppGCT/Pages/Precario/Index.cshtml
AppGCT/Pages/Precario/Index.cshtml.cs

Correção de bug's e aperfeiçoamento do preçário público para ser criado dinâmicamente

Rubricas e Preçário Público

---

AppGCT/AppGCT.csproj
AppGCT/Areas/Identity/Pages/Account/Manage/Index.cshtml.cs
AppGCT/Data/AppGCTContext.cs
AppGCT/Migrations/20230622194245_planomensalidades.Designer.cs
AppGCT/Migrations/20230622194245_planomensalidades.cs
AppGCT/Models/Epoca.cs
AppGCT/Models/Ginasta.cs
AppGCT/Models/PlanoMensalidade.cs
AppGCT/Models/PlanoMensalidades.cs
AppGCT/Pages/Gestao/Index.cshtml
AppGCT/Pages/Gestao/PlanoMensalidades/AcessDenied.cshtml
AppGCT/Pages/Gestao/PlanoMensalidades/AcessDenied.cshtml.cs
AppGCT/Pages/Gestao/PlanoMensalidades/Create.cshtml
AppGCT/Pages/Gestao/PlanoMensalidades/Create.cshtml.cs
AppGCT/Pages/Gestao/PlanoMensalidades/Delete.cshtml
AppGCT/Pages/Gestao/PlanoMensalidades/Delete.cshtml.cs
AppGCT/Pages/Gestao/PlanoMensalidades/Details.cshtml
AppGCT/Pages/Gestao/PlanoMensalidades/Details.cshtml.cs
AppGCT/Pages/Gestao/PlanoMensalidades/Edit.cshtml
AppGCT/Pages/Gestao/PlanoMensalidades/Edit.cshtml.cs
AppGCT/Pages/Gestao/PlanoMensalidades/Index.cshtml
AppGCT/Pages/Gestao/PlanoMensalidades/Index.cshtml.cs
AppGCT/Pages/Inscricoes/InscricaoEpoca/Create.cshtml.cs
AppGCT/Pages/Inscricoes/InscricaoEpoca/Index.cshtml

Criação Model Plano Mensalidades;
Criação CRUD Plano Mensalidades;
Inclusão de Botão para consulta do plano nas inscrições (sócios);
Inclusão de Botão para CRUD na gestão (admin);
Criação do plano automaticamente na inscrição (create apenas, falta Edit)

Plano mensalidades

---

AppGCT/Migrations/20230627181021_initialCreate2.Designer.cs
AppGCT/Migrations/20230627181021_initialCreate2.cs
AppGCT/Models/Rubrica.cs
AppGCT/Pages/Gestao/RubricasPrecario/Create.cshtml
AppGCT/Pages/Gestao/RubricasPrecario/Create.cshtml.cs
AppGCT/Pages/Gestao/RubricasPrecario/Delete.cshtml
AppGCT/Pages/Gestao/RubricasPrecario/Details.cshtml
AppGCT/Pages/Gestao/RubricasPrecario/Edit.cshtml
AppGCT/Pages/Gestao/RubricasPrecario/Index.cshtml
AppGCT/Pages/Gestao/Utilizadores/Create.cshtml.cs
AppGCT/Pages/Inscricoes/Ginastas/Index.cshtml
AppGCT/Pages/Inscricoes/Ginastas/Index.cshtml.cs
AppGCT/Pages/Inscricoes/InscricaoEpoca/Create.cshtml.cs

- Inclusão dos campos Indicador Pagamento inicial e TipoRubrica no model Rubrica;
- Inclusão dos novos campos da Rubrica no CRUD Rubricas;
- Fix no Create Rubrica;
- Correção CRUD utilizadores - Role Ginásio não pode criar outros Ginásio (conforme reunião);
- Inclusão de filtros por NomeGinasta e NomeSocio no Index.html Ginastas;
- Inclusão de sort's no Index.html Ginastas
Inclusão de validações na Inscrição Ginasta na Época nomeadamente:
- Validação se data inscrição se encontra entre Data inicio època -2 meses e Data Fim época;
- Criação de Plano Mensalidades entre data inscrição e Data Fim Época;

Plano mensalidades fixes

---

AppGCT/Areas/Identity/Pages/Account/ResendEmailConfirmation.cshtml.cs
AppGCT/Pages/Gestao/RubricasPrecario/Edit.cshtml

Correção bug que inicializava o valor unitário e ordem no preçário público sempre que era editado algum campo da rúbrica;

Bug Rúbricas Preçário no Modo Editar

---

AppGCT/Pages/Gestao/PlanoMensalidades/Index.cshtml
AppGCT/Pages/Gestao/RubricasPrecario/Index.cshtml
AppGCT/Pages/Gestao/RubricasPrecario/Index.cshtml.cs

Inclusão de filtros (individuais) nas Rúbricas Preçário (Index)

Filtros v4

---

AppGCT/Pages/Gestao/Movimentos/Details.cshtml.cs
AppGCT/Pages/Gestao/Movimentos/Index.cshtml
AppGCT/Pages/Gestao/Movimentos/Index.cshtml.cs
AppGCT/Pages/Shared/_Layout.cshtml

Inclusão de filtros por Sócio e Ginasta nos Movimentos;
**Em Falta!!!!
-incluir filtro entre datas;
-resolver bug como mostrar movimentos de quotas no role Sócio;**

Filtros Movimentos

---

AppGCT/Areas/Identity/Pages/Account/Register.cshtml.cs
AppGCT/Data/AppGCTContext.cs
AppGCT/Migrations/20230724195439_initialCreate.Designer.cs
AppGCT/Migrations/20230724195439_initialCreate.cs
AppGCT/Migrations/AppGCTContextModelSnapshot.cs
AppGCT/Models/Saldo.cs
AppGCT/Pages/Gestao/CobrancaMensalidades/Index.cshtml
AppGCT/Pages/Gestao/CobrancaMensalidades/Index.cshtml.cs
AppGCT/Pages/Gestao/Utilizadores/Create.cshtml.cs
AppGCT/Pages/Gestao/Utilizadores/Index.cshtml.cs
AppGCT/Pages/Shared/_Layout.cshtml

-Novo Model Saldo;
-Inserção de registo inicial na tabela Saldo no Registo via app e via painel Admin;
-Inicio da Cobrança Mensalidades (a pedido);

Saldos e Cobranças Mensalidade

---

AppGCT/Pages/Inscricoes/InscricaoEpoca/Create.cshtml.cs

Lançamento cobranças iniciais na inscrição (Create)
São lançadas todas as rubricas ativas, marcadas como iniciais e com valor unitário > 0

Cobranças iniciais na inscrição época

---

AppGCT/Areas/Identity/Data/Utilizador.cs
AppGCT/Areas/Identity/Pages/Account/Register.cshtml.cs
AppGCT/Data/ModelBuilderExtensions.cs
AppGCT/Migrations/20230801101013_initialCreate.Designer.cs
AppGCT/Migrations/20230801101013_initialCreate.cs
AppGCT/Migrations/20230801103112_addRoleToUserTable.Designer.cs
AppGCT/Migrations/20230801103112_addRoleToUserTable.cs
AppGCT/Migrations/20230801114201_addBalanceToMovimentoTable.Designer.cs
AppGCT/Migrations/20230801114201_addBalanceToMovimentoTable.cs
AppGCT/Migrations/20230801144615_addErroRubricaObrigatoria.Designer.cs
AppGCT/Migrations/20230801144615_addErroRubricaObrigatoria.cs
AppGCT/Models/Movimento.cs
AppGCT/Pages/Gestao/Movimentos/Create.cshtml
AppGCT/Pages/Gestao/Movimentos/Create.cshtml.cs
AppGCT/Pages/Gestao/Movimentos/Index.cshtml
AppGCT/Pages/Gestao/Movimentos/Index.cshtml.cs
AppGCT/Pages/Gestao/Utilizadores/Create.cshtml.cs
AppGCT/wwwroot/css/site.css

Fica a faltar, na componente d eMovimentos:
Acrescentar Tipo de Rubrica Regularização, a débito e Credito
Ajustar Edit, para nao permitir a ninguem editar o movimento( alteração já no branch Movimentos_v2)
Rever definições dos models, para limitar tamanho dos campos
Acrescentar checkbutton para aplicar, ou não desconto parametrizado (atualemte, funcionalm,ente só o pagamento por transferencia bancaria permite desconto de 1 euro)

Movimentos v3

---

AppGCT/Areas/Identity/Pages/Account/Register.cshtml.cs
AppGCT/Data/ModelBuilderExtensions.cs
AppGCT/Migrations/20230825233156_initialcreate.Designer.cs
AppGCT/Migrations/20230825233156_initialcreate.cs
AppGCT/Migrations/AppGCTContextModelSnapshot.cs
AppGCT/Pages/Gestao/Utilizadores/Create.cshtml
AppGCT/Pages/Gestao/Utilizadores/Create.cshtml.cs
AppGCT/Pages/Gestao/Utilizadores/Delete.cshtml.cs
AppGCT/Pages/Gestao/Utilizadores/Edit.cshtml
AppGCT/Pages/Gestao/Utilizadores/Edit.cshtml.cs
AppGCT/Pages/Inscricoes/Ginastas/Delete.cshtml
AppGCT/Pages/Inscricoes/Ginastas/Details.cshtml
AppGCT/Pages/Inscricoes/Ginastas/Edit.cshtml.cs
AppGCT/Pages/Inscricoes/InscricaoEpoca/Create.cshtml.cs

-Inclusão de validações (inclui NIF) no registo página inicial e no Create/Edit dos Utilizadores;
-Inclusão de validação no Delete Utilizadores que não permite ao próprio utilizador (se for admin ou Ginásio) apagar-se do sistema;
-Inclusão validações NIF no Edit dos Ginastas;
-Inclusão de resize da imagem do ginasta (mostra 150x150) no Details/Delete;
-Inclusão no Create da InscricaoEpoca para assegurar que só é possivel uma Inscrição por Época para cada Ginasta;
-Seed inicial carrega automaticamente Época, descontos, metodos, classes e rúbricas;

Fixes 250823

---

AppGCT/Pages/Gestao/CobrancaMensalidades/Index.cshtml.cs
AppGCT/Pages/Gestao/Movimentos/Details.cshtml.cs
AppGCT/Pages/Gestao/PlanoMensalidades/Edit.cshtml.cs

-Atualização do mês para lançamento das quotas anuais de sócio (foi definido como Outubro para efeitos de apresentação do projeto mas deverá ser em Janeiro)
-Correção bug no Details Movimentos;
-Role Ginásio pode atualizar Plano Mensalide;

Update mes cobrança automatica

---

AppGCT/Pages/Estatisticas/Index.cshtml
AppGCT/Pages/Estatisticas/Index.cshtml.cs
AppGCT/Pages/Estatisticas/IndexInscricoes.cshtml
AppGCT/Pages/Estatisticas/IndexInscricoes.cshtml.cs
AppGCT/Pages/Estatisticas/IndexMovimentos.cshtml
AppGCT/Pages/Estatisticas/IndexMovimentos.cshtml.cs
AppGCT/Pages/Gestao/CobrancaMensalidades/Index.cshtml.cs
AppGCT/Pages/Shared/_Layout.cshtml

Inclusão de Index de Estatísticas que contém informação sobre:
- Utilizadores do Sistema (tipo de role, contador de ativos e inativos);
- Ginastas (contador de ativos e inativos);
- Inscrições por Época (Época, e contador de nº inscrições) - Inclui botão para ver detalhe das inscrições;
- Movimentos por Época ( Época, nº de movimentos, somatório de movimentos a débito/crédito e saldo final) - Inclui Botão para ver detalhe dos movimentos ( que mostra os totais por rubrica);

Estatisticas
